theme: jekyll-theme-cayman

title: Github Repos | Aninthan
description: This is where I post what I learn
linkedin: https://www.linkedin.com/in/aninthan-r/

social-network-links:
  name: Aninthan Ramaswamy
  email: ramaswan@mail.uc.edu
  linkedin: aninthan-r/
  github: aninthan-ramaswamy