theme: jekyll-theme-cayman

title: Github Repos | Aninthan
description: This is where I post what I learn

social-network-links:
  name: Aninthan Ramaswamy
  email: ramaswan@mail.uc.edu
  linkedin: aninthan-r/
  github: aninthan-ramaswamy
